# Generated by Django 5.0.2 on 2024-02-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_description', models.CharField(max_length=100)),
                ('date_register', models.DateTimeField(auto_now_add=True)),
                ('date_delivery', models.DateTimeField()),
                ('date_complete', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
